# Generated by Django 6.0.3 on 2026-05-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0004_workday'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacationschedule',
            unique_together={('year', 'department')},
        ),
        migrations.AlterField(
            model_name='vacationschedule',
            name='department',
            field=models.CharField(max_length=100, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='vacationschedule',
            name='min_employees',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='vacationschedule',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
        migrations.RemoveField(
            model_name='vacationschedule',
            name='published_at',
        ),
    ]
