# Generated by Django 6.0.3 on 2026-06-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0005_alter_vacationschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_active_employees', models.PositiveIntegerField(default=1, verbose_name='Минимальное количество сотрудников на месте')),
            ],
        ),
    ]
